#!/usr/bin/env sh
alias clear-swaps="rm -rf ~/.local/share/nvim/swap"
alias weather="curl wttr.in"
alias vim="nvim"
alias ls="lsd -la"
alias news="newsboat"
alias rebase="git rebase -i"
alias gd="git diff --color | diff-so-fancy"
alias bn="buku -a"
alias da="direnv allow"
alias mb="make build"
alias mt="make test"
alias mp="make plan"
alias ma="make apply"
alias mr="make run"
alias mbr="make build run"
alias mc="make clean"
alias derek="make"
alias in='task add +in'
alias cicd='make build run test push && TAG=dev make build push && TAG=prod make build push clean'
alias mbp='make build push'
