#!/usr/bin/env sh
export EDITOR='vim'
export PATH=$PATH:$HOME/bin:$HOME/dots/bin:$HOME/dev/bin

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin
