#!/usr/bin/env sh

mkdir -p $HOME/.newsboat
mkdir -p $HOME/bookmarks/

rm -f $HOME/.vimrc
rm -f $HOME/.zshrc
rm -f $HOME/.tmux.conf
rm -f $HOME/.hyper.js
rm -f $HOME/.gitconfig

ln -sf $HOME/dots/.newsboat/urls $HOME/.newsboat/urls
ln -sf $HOME/dots/.newsboat/config $HOME/.newsboat/config
ln -sf $HOME/dots/.neomuttrc $HOME/.neomuttrc
ln -sf $HOME/dots/.vimrc $HOME/.vimrc
ln -sf $HOME/dots/.zshrc $HOME/.zshrc
ln -sf $HOME/dots/.tmux.conf $HOME/.tmux.conf
ln -sf $HOME/dots/.hyper.js $HOME/.hyper.js
ln -sf $HOME/dots/.gitconfig $HOME/.gitconfig
ln -sf $HOME/dots/.taskrc $HOME/.taskrc
ln -sf $HOME/dots/.zshrc $HOME/dots/etc/emacs-vterm-zsh.sh
ln -sf $HOME/dots/.emacs.d/init.el $HOME/.emacs.d/init.el
