
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='arxiv',
    version='0.1.0',
    python_requires='==3.*,>=3.8.0',
    author='chrisaddy',
    author_email='chris.william.addy@gmail.com',
    entry_points={"console_scripts": ["arxiv = arxiv.cli:app"]},
    packages=['arxiv'],
    package_dir={"": "."},
    package_data={},
    install_requires=['bs4==0.*,>=0.0.1', 'lxml==4.*,>=4.5.2', 'pandas==1.*,>=1.1.3', 'requests==2.*,>=2.24.0', 'typer==0.*,>=0.3.2'],
    extras_require={"dev": ["dephell==0.*,>=0.8.3", "dephell-setuptools==0.*,>=0.2.4", "typer-cli==0.*,>=0.0.11"]},
)
